apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eschool-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "${static_ip}"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: eschool-frontend
          servicePort: 80
      - path: /api 
        backend:
          serviceName: eschool-api
          servicePort: 8080
